apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-{{ .Values.name }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.url }}
      http:
        paths:
          - pathType: ImplementationSpecific
            path: "/"
            backend:
              service:
                name: frontend-{{ regexReplaceAll "\\W+" .Values.version "-" }}
                port:
                  number: 8080
  {{- if .Values.ingress.customUrl }}
    - host: {{ .Values.ingress.customUrl }}
      http:
        paths:
          - pathType: ImplementationSpecific
            path: "/"
            backend:
              service:
                name: frontend-{{ regexReplaceAll "\\W+" .Values.version "-" }}
                port:
                  number: 8080
  {{- end }}