apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-customers-base
spec:
  generators:
    - git:
        repoURL: https://github.com/thschue/frontend-demo.git
        revision: HEAD
        files:
          - path: demo/customers/**/config.yaml
  template:
    metadata:
      name: 'customer-{{ path.basename }}'
    spec:
      project: default
      source:
        path: charts/customer
        repoURL: https://github.com/thschue/frontend-demo.git
        targetRevision: HEAD
        helm:
          parameters:
            - name: "frontend"
              value: '{{ frontend }}'
            - name: "name"
              value: '{{ path.basename }}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{ namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true